"""changed db structre

Revision ID: 07fe3a537ce6
Revises: 83c2f8c97836
Create Date: 2023-09-07 14:29:38.903731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fe3a537ce6'
down_revision = '83c2f8c97836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
